title: getting-started-crumble
hero_image: images/banner.png
description: getting-started-crumble description
version: 4
listed: false
copyedit: false
last_tested: "2019-03-06"
steps:
  - title: Introduction
  - title: Connecting the Crumble controller
  - title: Connecting battery power
  - title: step 4
