title: getting-started-crumble
hero_image: images/banner.png
description: getting-started-crumble description
version: 4
listed: false
copyedit: false
last_tested: "2019-03-06"
steps:
  - title: Introduction
  - title: Setting up the Crumble controller
  - title: Crumble Sparkles
  - title: LEDs
  - title: "Challenge: flashing LED"
    challenge: true
  - title: Colour sequences
  - title: Two Sparkle sequencing
  - title: "Challenge: follow me colour sequence"
    challenge: true
  - title: Sparkle creations 